version: '3.8'
services:
  db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_PASSWORD: password
    ports:
      - 4306:3306
    volumes:
      - mysql-db:/var/lib/mysql
  backend:
    tty: true
    depends_on:
      - db
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
      - rust-target:/app/target
      - cargo-cache:/usr/local/cargo/registry
    command: /bin/sh -c "cargo watch --poll -x 'run'"
    working_dir: /app
    environment:
      DB_HOST: db
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    command:  sh -c "npm install && npm run dev"
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - '8000:3000'
volumes:
  rust-target:
    driver: local
  cargo-cache:
    driver: local
  mysql-db:
    driver: local